### ISSUE TITLE
メモ：修正タスク一覧

### ISSUE THREAD

**Issue by Agron4066** [hyperkinoko/portfolio#1]
### body外
- [x] ファイル名に大文字を入れない
- [x] favicon設定
　
### body全体
- [x] wrapper祭り修正
　
### header部
- [x] 「Future for you.」opacity、font-size（sp）修正
- [x] スクロールバーの球が線の始まりから始まるようにする
　
### navi部
- [x] 画面から横幅がはみ出ている（sp）。
　
### Works部
- [x] 波線が無くなる
- [x] site-buttonの遷都先を別タブで開くようにする。
　
### Profile部
- [x] profile部分のアニメーションが挙動が気になる(画面上に出てくるまで表示されているようなので非表示にする)
　
### About部
- [x] 波線が無くなる。
- [x] div class="table"をtableに。
- [x] スマホで見た時、Aboutのスタッフ数の下が空いてる。

**Comment by Agron4066** [comment]
「About部の表をtableタグに。」のコミットですが、scssをaddし忘れました。
scssの当該変更箇所は、
「wrapper祭りを解消」のタグに含まれます。

**Comment by Agron4066** [comment]
「波線が無くなる」現象ははじめ隣接する要素のmarginに押しつぶされているのかと思いましたが、違いました。
以下２つのコミットを無視してください。revertしましたが、うまくrevertできたか自信が無いです。
- 5c05f15ddbc576e68b26ec095c830e7e7ce9eb1c　「波線が消えないための対処←marginがはみ出す場所(と怪しい要素)にoverflow: hidden;を当てた。」
- aa20bbb7f23f439c312301c375c928862117a438　「overflow: hidden;の漏れを修正→波線が消えることへの対処」

真の理由はパス違いでした。
github pages上で見たときにパスの冒頭の「../」が削除されてしまっています。デベロッパーツール上で「../」を追記すると、波線が見えるようになります。WordPressみたいに一部のコードが書き換わったりするのでしょうか？調べてみましたが情報を見つけられませんでした。
　
ひとまずmixinを使うのを辞めて各所に直接書くようにしました。
これでうまくいく確証はないのですが、これで試してみてください。
　
もったいないので当初のmixinをここに保存します。
```
@mixin bg-img($img-name:works-bg) {
  background: {
    image: url("../img/#{$img-name}.png");
    repeat: no-repeat;
    position: top;
    size: 100%;
  }
}
```

**Comment by hyperkinoko** [comment]
meeeeeeeeeerrrrrrrrged!!!!!
